CFLAGS= -O2 -ffast-math -fPIC -DSET_BZERO=0 -Wall -I../libmisc -I../libastro

OBJS =	\
	align2fits.o	\
	fits.o		\
	fitscorr.o	\
	filters.o	\
	fitsip.o

libfits.so:	$(OBJS)
	gcc -shared -o $(DEFS) $@ $(OBJS)

pass2: install

install: libfits.so
	rm -f $(TELHOME)/lib/libfits.so
	cp libfits.so $(TELHOME)/lib/libfits.so

libfits.a:	$(OBJS)
	ar rv $@ $(OBJS)

clobber:
	touch x.o
	rm -f *.o libfits.a libfits.so

