CFLAGS= -DTEST_IT -O2 -ffast-math -Wall -I. -I../libastro
LDFLAGS = -L. -L../libastro
LIBS = -lmisc -lastro -lm

funcmax: funcmax.o
	$(CC) $(LDFLAGS) -o funcmax funcmax.o $(LIBS)

newton: newton.o
	$(CC) $(LDFLAGS) -o newton newton.o $(LIBS)

telaxes: telaxes.o
	$(CC) $(LDFLAGS) -o telaxes telaxes.o $(LIBS)
