#!/bin/tcsh -f

if(`whoami` != "root") then
   echo enter root password
   su -c ./update_cdbuilder
   exit
endif

cd ./cdbuilder
tar --exclude CVS -cf - . | (cd /home/cdbuilder; tar xf -)
cp ../../../manual/*.* /home/cdbuilder/manual

