#!/bin/csh -f
# go to home in given dir at given vel, waiting up to timeout.
# exit 0 if ok, else issue message and exit 1

if ($#argv != 4) then
    echo $0':' axis vel timeout dir
    exit 1
endif

set ax = $argv[1]
set vl = $argv[2]
set to = $argv[3]
set dr = $argv[4]
if ($dr != 'm' && $dr != 'r') then
    echo home dir must be m or r
    exit 1
endif

onintr stop

pc39cmd "a$ax vl$vl h${dr}0"
stopTO $ax $to
if ($status) then
    echo seeking $dr home timed out
    pc39cmd kl
    exit 1
endif
exit 0

stop:
pc39cmd "a%ax st"
exit 1
