#!/usr/bin/perl

# check DPAGE: should see 32 distinct 4k pages mapped to 7000
for ($i = 0; $i < 32; $i++) {
    printf ("w DPAGE %x\n", $i);
    printf ("w 7000 \"hello world %x\"\n", $i);
}

for ($i = 0; $i < 32; $i++) {
    printf ("w DPAGE %x\n", $i);
    printf ("d 7000 700f\n");
}

for ($i = 1; $i < 8; $i++) {
    printf ("d %x000 %x00f\n", $i, $i);
}

# check PPAGE: should see 8 distinct 16k pages mapped to 8000
for ($i = 0; $i < 8; $i++) {
    printf ("w PPAGE %x\n", $i);
    printf ("w 8000 \"hello top %x\"\n", $i);
}

for ($i = 0; $i < 8; $i++) {
    printf ("w PPAGE %x\n", $i);
    printf ("d 8000 800f\n");
}

printf ("d c000 c00f\n");
