#!/bin/csh -f

# first move them away
pc39cmd -v 'ax vl150000 ac50000 mr-2000000 go qa'
pc39cmd -v 'ay vl150000 ac50000 mr-2000000 go qa'
pc39cmd -v 'az vl100000 ac50000 mr-1000000 go qa'
pc39cmd -v 'au vl100000 ac50000 mr-1000000 go qa'
pc39cmd -v 'av vl100000 ac50000 mr1000000  go qa'

# wait for all motions to stop
set xv = 123;
set yv = 123;
set zv = 123;
set uv = 123;
set vv = 123;
while ("$xv" > 0 || "$yv" > 0 || "$zv" > 0 || "$uv" > 0 || "$vv" > 0)
    set xv = `pc39cmd -v "ax rv"`
    set yv = `pc39cmd -v "ay rv"`
    set zv = `pc39cmd -v "az rv"`
    set uv = `pc39cmd -v "au rv"`
    set vv = `pc39cmd -v "av rv"`
    echo ""
    sleep 1
end

# now start them all 
AltHome &
AzHome &
FocusHome &
FilterHome &
RotHome &

# and wait
wait

# prove it
pc39cmd -v 'ax qa'
pc39cmd -v 'ay qa'
pc39cmd -v 'az qa'
pc39cmd -v 'au qa'
pc39cmd -v 'av qa'
