#!/bin/csh -f

pc39 << _EOF_
# Run the az motor from limit to limit forever
# we assume it starts in the center.

ax			# select the az axis 
ln			# limits on
ac200000 vl250000	# set max accel and vel
# wh ma-14000000 go ma14000000 go wg # full range is 31,211,520
wh mr-100000 go mr100000 go wg # full range is 31,211,520

_EOF_

echo Hit RETURN to stop ax ..
$<

pc39cmd 'ax st'
