#!/usr/bin/perl -- -*- ATF -*-
# submit_sched.pl: digest output from submit_sched.html and produce a report.
# Elwood Downey
# 12 Apr 96: begin
# 17 Jun 96: check for valid obs id.
#  2 Nov 98: add Scope parameter to select target telescope.
# version number
$ver = 1.2;

# handy extras
require "cgi-lib-97.pl";
require "ctime.pl";

# number of rows in submit_sched.html form
$nrows = 5;

# Read in all the variables set by the form so we can access as $input{'name'}
&ReadParse(*input);

# Print the HTML header once
print "Content-type: text/html\n\n";
print "<html><head>\n";
print "</head>\n<body bgcolor=#ffffff text=#000000>\n";

# get which scope and set supporting values accordingly
# scope_name: full scope name
# scope_abbr: scope name abbreviation
# scope_telhome: OCAAS base
# scope_schdir: dir to place resulting .sch file
# scope_chksch: which chksch to run
# scope_obstxt: list of current observer codes
$scope = $input{'Scope'};
if ($scope eq "IRO") {
    $scope_name = "Iowa Robotic Observatory";
    $scope_abbr = "IRO";
    $scope_telhome = "/net/iro/usr/local/telescope";
    $scope_schdir = "/net/iro/usr/local/telescope/user/schedin/netin";
    $scope_chksch = "/net/iro/usr/local/telescope/bin/chksch";
    $scope_obstxt = "/net/iro/home/ocaas/obs.txt";
} elsif ($scope eq "ATF") {
    $scope_name = "Automated Telescope Facility";
    $scope_abbr = "ATF";
    $scope_telhome = "/net/atf/usr/local/telescope";
    $scope_schdir = "/net/atf/usr/local/telescope/user/schedin/netin";
    $scope_chksch = "/net/atf/usr/local/telescope/bin/chksch";
    $scope_obstxt = "/net/atf/home/ocaas/obs.txt";
} else {
    &errmsg ("Unsupported Scope code: $scope\n");
    goto wrapup;
}

# confirm the scope we are working for.
print "<B>$scope_name Schedule Submission Check</B>\n";

# set TELHOME env so all tools find correct config files, etc.
$ENV{TELHOME} = $scope_telhome;

# get and verify valid observer code
$obc = $input{'Obscode'};
$obc =~ s/ //g;
if ($obc eq "") {
    &errmsg ("Missing Observer code\n");
    goto wrapup;
}
$rc = `./obsok $obc $scope_obstxt`;
if ($rc == 0) {
    &errmsg ("Invalid Observer code: $obc\n");
    goto wrapup;
}

# form basename of sched file in $schfnb and full path in $schfn
my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = gmtime(time);
$daynr = $yday;
$schfnb = "$obc$daynr.sch";
$schfn = "$scope_schdir/$schfnb";

# check that there is a finite title 
$title = $input{'Title'};
if ("$title" eq "") {
    &errmsg ("Please include a title for later reference.\n");
    goto wrapup;
}

# allow only one request per day.
if (-e $schfn) {
    &errmsg ("Please, only one request per UTC day; thank you.\n");
    goto wrapup;
}

# create the schedule file as file handle SF
if (!open (SF,">$schfn")) {
    &errmsg ("Cannot create $schfn\n");
    goto wrapup;
}

# put in the fixed initial fields
printf SF "! Generated by submit_sched.pl Version $ver\n";
printf SF "! For the %s.\n", $scope_name;
printf SF "! From %s (%s)\n", $ENV{'REMOTE_HOST'}, $ENV{'REMOTE_ADDR'};
printf SF "! As Observer Code \"%s\"\n", $input{'Obscode'};
printf SF "! On %s", `date -u`;
printf SF "! With %s\n", $ENV{'HTTP_USER_AGENT'};
printf SF "\n";

printf SF "TITLE = '%s'\n", $input{"Title"};
printf SF "OBSERVER = '%s'\n", $input{'Observer'};

# now build the block/repeat entries from each defined row
for ($i = 0; $i < $nrows; $i++) {
    # an empty source name means this row is not in use
    $src = $input{"Src$i"};
    if ($src eq "") { next; }

    # always starts with this
    printf SF "\n! Scan set %d\n", $i+1;

    # repeat count -- count is used in overall BLOCKREPEAT
    $rpc = $input{"RpC$i"};
    
    # Set Repeat Gap - keyword for BLOCK
    $rpd = $input{"RpD$i"};
    $rpd = "1:0:0" if ($rpd eq "");
    printf SF "BLOCK = '%s' \n", $rpd;

    # set source and catalog or ra/dec
    $ref = $input{"Ref$i"};
    if ($ref eq "Cat") {
	printf SF "    SOURCE = '%s'\n", $src;
    } else {
	$ra = $input{"RA$i"};
	$dec = $input{"Dec$i"};
	$epo = $input{"Epo$i"};
	printf SF "    SOURCE = '%s' RA = '%s' Dec = '%s' Epoch = '%s'\n",
							$src, $ra, $dec, $epo;
    }

    # filter and duration sets
    $fil = $input{"Ftr$i"};
    $dur = $input{"Dur$i"};
    printf SF "    FILTER = '%s' DURATION = '%s'\n", $fil, $dur;

    # LST or HA start time.
    $stt = $input{"Stt$i"};
    if ($stt ne "") {
	$lstha = $input{"LstHA$i"};
	if ($lstha eq "HA") {
	    printf SF "    HASTART = '%s'\n", $stt;
	} else {
	    printf SF "    LSTSTART = '%s'\n", $stt;
	}
    }
   
    # compression scale
    $cmp = $input{"Cmp$i"};
    if ($cmp > 0) {
	printf SF "    COMPRESS = '%s'\n", $cmp;
    }

    # comment
    $cmt = $input{"Cmt$i"};
    if ($cmt ne "") {
	printf SF "\n    COMMENT = '%s'\n\n", $cmt;
    }
    # finished with this block
    printf SF "    /\n";
    printf SF "BLOCKREPEAT %d\n", $rpc <= 1 ? 1 : $rpc;
}

# phew
close (SF);

# copy out the schedule file in a <pre></pre> block
print "<p><font color=\"red\" size=6>\nContents of schedule file $schfnb:</font>\n<p><pre>\n";
open (SCHFN, "<$schfn");
while (<SCHFN>) {
    print $_;
}
close (SCHFN);
print "</pre><p>\n";

#execute chksch to check quality of candidate schedule file
$reply=`$scope_chksch $schfn 2>&1`;
if ($reply ne "")  {
    &errmsg ($reply);
} else {
    printf "<p><b>";
    printf " Your schedule has been successfully submitted"; 
    printf " and assigned reference ID <em>%s</em>.", "$obc$daynr";
    printf " Please make a note of the ID for later reference.\n";
    printf "</b>";
open (SCHFN, "<$schfn");
}
 
wrapup:

# final boilerplate
print <<ENDOFTEXT;
</body></html>
ENDOFTEXT

# print error message in @_ to output, then close SCHFN and unlink $schfn.
sub errmsg {
    local($msg) = @_;
    print "<p><h3><blink>\nUnsuccessful!\n</h3></blink>\n";
    printf "<h3>Error:\n<pre>\n%s\n</pre></h3>\n\n", $msg;
    close (SCHFN);
    unlink ($schfn);

    print "<p>Use your browser's \"Back\" feature to reedit the same request.\n";
}
